name: OpenApi Checks

on:
  workflow_call:
    inputs:
      openapi-file-path:
        type: string
        required: true    

env:
  RULE_VERSION: 10
  
jobs:
  OWASP-CHECK:    
    runs-on: ubuntu-latest
    env:
       SPECTRAL_OWASP_RULESET_LOCATION: https://raw.githubusercontent.com/TechnicalFreak/fop.openapi-rules/${{env.RULE_VERSION}}/spectral-security.yml
    steps:      
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install -g @stoplight/spectral-cli
      - run: npm install --save -D @stoplight/spectral-owasp-ruleset
      - run: wget $SPECTRAL_OWASP_RULESET_LOCATION -O .spectral.yml
      - run: spectral lint ${{github.event.inputs.openapi-file-path}}

  OAS-CHECK:    
    runs-on: ubuntu-latest
    env:
      SPECTRAL_OAS_RULESET_LOCATION: https://raw.githubusercontent.com/TechnicalFreak/fop.openapi-rules/${{env.RULE_VERSION}}/spectral-oas.yml
    steps:      
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install -g @stoplight/spectral-cli
      - run: wget $SPECTRAL_OAS_RULESET_LOCATION -O .spectral.yml
      - run: spectral lint ${{github.event.inputs.openapi-file-path}}

  STYLEGUIDE-CHECK:    
    runs-on: ubuntu-latest
    env:
      SPECTRAL_STYLEGUIDE_RULESET_LOCATION: https://raw.githubusercontent.com/TechnicalFreak/fop.openapi-rules/${{env.RULE_VERSION}}/spectral-styleguide.yml
    steps:      
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install -g @stoplight/spectral-cli
      - run: wget $SPECTRAL_STYLEGUIDE_RULESET_LOCATION -O .spectral.yml
      - run: spectral lint ${{github.event.inputs.openapi-file-path}}
